from __future__ import annotations


# Handheld Controller Operation Guide for OpenXR Link, can be easily extended for in-game usage.
# ROWS is the normal no-room viewer guide. ENV_ROWS overrides only the room
# viewer guide, while shared controller mappings stay in the same shape.
def get_controller_help_rows(lang):
    if lang == "CN":
        ROWS = [
            ("# 手柄操作指南", "", "", True),
            ("", "", "", False),

            ("[屏幕位置与姿态]", "", "", True),
            ("左握持 + 激光指屏幕", "按住移动或旋转", "屏幕垂直平移或90度旋转", False),
            ("右握持 + 激光指屏幕", "按住移动或旋转", "头部球面旋转或任意旋转", False),
            ("双握持 + 激光指屏幕", "按住移动", "双手中心点移动", False),
            ("左握持 + 左摇杆 左右", "按住推动", "屏幕偏摆旋转", False),
            ("左握持 + 左摇杆 前后", "按住推动", "屏幕俯仰旋转", False),
            ("右握持 + 右摇杆 左右", "按住推动", "屏幕尺寸调整", False),
            ("右握持 + 右摇杆 前后", "按住推动", "屏幕距离调整", False),
            ("", "", "", False),

            ("[预设与杂项]", "", "", True),
            ("左 Menu 键", "短按", "循环显示: 隐藏/FPS左下角/FPS+快捷键指南", False),
            ("左 Y 键", "短按", "恢复默认居中显示", False),
            ("左 Y 键", "长按 1s", "循环屏幕预设", False),
            ("左 X 键", "短按", "显示/隐藏虚拟键盘", False),
            ("左 X 键", "长按 1s", "切换环境天空盒/黑色背景", False),
            ("右 A 键", "短按", "屏幕曲面/平面切换", False),
            ("右 A 键", "长按 1s", "循环显示: 隐藏/FPS左下角/FPS+快捷键指南", False),
            ("右 B 键", "短按", "切换VDXR绿屏/背景色", False),
            ("右 B 键", "长按 1s", "显示/隐藏操作指南", False),
            ("左右扳机", "同时长按 5s", "禁用/启用手柄；禁用时仅此组合有效", False),
            ("", "", "", False),

            ("[深度与视觉]", "", "", True),
            ("右握持 + 左摇杆 前后", "按住推动", "调整深度强度", False),
            ("右握持 + 右摇杆按下", "按住单击", "重置深度强度", False),
            ("左握持 + 左摇杆按下", "按住单击", "切换2D和3D画面", False),
            ("", "", "", False),

            ("[鼠标与快捷键(激光指向屏幕时)]", "", "", True),
            ("右扳机", "全按单击", "鼠标左键单击", False),
            ("右扳机", "持续按住", "鼠标左键按住", False),
            ("左扳机", "全按单击", "鼠标右键单击", False),
            ("左扳机", "持续按住", "鼠标右键框选", False),
            ("右摇杆 前后", "按住推动", "鼠标滚轮滚动", False),
            ("左摇杆 前后", "按住推动", "键盘上下方向键", False),
            ("左摇杆 左右", "按住推动", "键盘左右方向键", False),
            ("左摇杆按下", "短按", "Ctrl+C", False),
            ("左摇杆按下", "长按 1s", "Ctrl+X", False),
            ("右摇杆按下", "短按", "Ctrl+V", False),
            ("右摇杆按下", "长按 1s", "回车键", False),
            ("", "", "", False),

            ("[虚拟键盘(仅键盘显示时)]", "", "", True),
            ("双握持 + 激光指键盘", "按住移动", "键盘绕头球面移动", False),
            ("右握持 + 左摇杆 左右", "按住推动", "键盘宽度缩放", False),
            ("右握持 + 左摇杆 前后", "按住推动", "键盘推拉距离", False),
            ("左握持 + 右摇杆 左右", "按住推动", "键盘偏摆偏移", False),
            ("左握持 + 右摇杆 前后", "按住推动", "键盘俯仰偏移", False),
            ("左握持 + 左摇杆按下", "按住移动", "键盘环绕头部位移", False),
            ("左/右扳机", "半按", "触发键盘按键", False),
            ("", "", "", False),

            ("[手柄模型校准(开发者)]", "", "", True),
            ("右 A+B 键", "同时按住 0.5s", "切换手柄品牌模型", False),
            ("右 A+B 键", "同时按住 5s", "进入/退出校准模式", False),
            ("右 B 键", "校准模式中单击", "保存校准并退出", False),
        ]
        ENV_ROWS = [
            ("# 房间模式手柄操作指南", "", "", True),
            ("", "", "", False),

            ("[房间与面板]", "", "", True),
            ("左 Menu 键", "短按", "循环状态面板: 隐藏/FPS左下角/FPS+快捷键指南", False),
            ("左 Y 键", "短按", "重新居中到房间屏幕/默认位置", False),
            ("左 Y 键", "长按 1s", "切换房间环境", False),
            ("左 X 键", "短按", "显示/隐藏虚拟键盘", False),
            ("左 X 键", "长按 1s", "切换环境天空盒/黑色背景", False),
            ("右 A 键", "短按", "屏幕曲面/平面切换", False),
            ("右 A 键", "长按 1s", "循环状态面板: 隐藏/FPS左下角/FPS+快捷键指南", False),
            ("右 B 键", "短按", "切换VDXR绿屏/背景色", False),
            ("右 B 键", "长按 1s", "显示/隐藏操作指南", False),
            ("左右扳机", "同时长按 5s", "禁用/启用手柄；禁用时仅此组合有效", False),
            ("", "", "", False),

            ("[深度与视觉]", "", "", True),
            ("右握持 + 左摇杆 前后", "按住推动", "调整深度强度", False),
            ("右握持 + 右摇杆按下", "按住单击", "重置深度强度", False),
            ("左握持 + 左摇杆按下", "按住单击", "切换2D和3D画面", False),
            ("", "", "", False),

            ("[鼠标与快捷键(激光指向屏幕时)]", "", "", True),
            ("右扳机", "全按单击", "鼠标左键单击", False),
            ("右扳机", "持续按住", "鼠标左键按住", False),
            ("左扳机", "全按单击", "鼠标右键单击", False),
            ("左扳机", "持续按住", "鼠标右键框选", False),
            ("右摇杆 前后", "按住推动", "鼠标滚轮滚动", False),
            ("左摇杆 前后", "按住推动", "键盘上下方向键", False),
            ("左摇杆 左右", "按住推动", "键盘左右方向键", False),
            ("左摇杆按下", "短按", "Ctrl+C", False),
            ("左摇杆按下", "长按 1s", "Ctrl+X", False),
            ("右摇杆按下", "短按", "Ctrl+V", False),
            ("右摇杆按下", "长按 1s", "回车键", False),
            ("", "", "", False),

            ("[虚拟键盘(仅键盘显示时)]", "", "", True),
            ("单/双握持 + 激光指键盘", "按住移动", "键盘绕头球面移动", False),
            ("右握持 + 左摇杆 左右", "按住推动", "键盘宽度缩放", False),
            ("右握持 + 左摇杆 前后", "按住推动", "键盘推拉距离", False),
            ("左握持 + 右摇杆 左右", "按住推动", "键盘偏摆偏移", False),
            ("左握持 + 右摇杆 前后", "按住推动", "键盘俯仰偏移", False),
            ("左握持 + 左摇杆", "按住推动", "键盘环绕头部位移", False),
            ("左/右扳机", "半按", "触发键盘按键", False),
            ("", "", "", False),

            ("[手柄模型校准(开发者)]", "", "", True),
            ("右 A+B 键", "同时按住 0.5s", "切换手柄品牌模型", False),
            ("右 A+B 键", "同时按住 5s", "进入/退出校准模式", False),
            ("右 B 键", "校准模式中单击", "保存校准并退出", False),
        ]
    else:
        ROWS = [
            ("# Controller Operation Guide", "", "", True),
            ("", "", "", False),

            ("[Screen Position & Orientation]", "", "", True),
            ("Left Grip + laser on screen", "Hold & move or twist", "Translate vertically or 90deg rotate", False),
            ("Right Grip + laser on screen", "Hold & move or twist", "Sphere-orbit or free rotate", False),
            ("Both Grips + laser on screen", "Hold & move", "Move by center of both hands", False),
            ("Left Grip + left stick L/R", "Hold & push", "Screen yaw rotation", False),
            ("Left Grip + left stick U/D", "Hold & push", "Screen pitch rotation", False),
            ("Right Grip + right stick L/R", "Hold & push", "Screen width adjustment", False),
            ("Right Grip + right stick U/D", "Hold & push", "Screen distance adjustment", False),
            ("", "", "", False),

            ("[Presets & Misc]", "", "", True),
            ("Left Menu button", "Short press", "Cycle panel: hidden/lower-left FPS/FPS + shortcut guide", False),
            ("Left Y button", "Short press", "Reset to default centered display", False),
            ("Left Y button", "Long press 1s", "Cycle screen presets", False),
            ("Left X button", "Short press", "Show/hide virtual keyboard", False),
            ("Left X button", "Long press 1s", "Toggle environment skybox / black", False),
            ("Right A button", "Short press", "Toggle curved/flat screen", False),
            ("Right A button", "Long press 1s", "Cycle panel: hidden/lower-left FPS/FPS + shortcut guide", False),
            ("Right B button", "Short press", "Toggle VDXR green / background", False),
            ("Right B button", "Long press 1s", "Show/hide operation guide", False),
            ("Both triggers", "Hold together 5s", "Disable/enable controllers; only this chord works while disabled", False),
            ("", "", "", False),

            ("[Depth & Visual]", "", "", True),
            ("Right Grip + left stick U/D", "Hold & push", "Adjust depth strength", False),
            ("Right Grip + right stick press", "Hold & click", "Reset depth strength", False),
            ("Left Grip + left stick press", "Hold & click", "Toggle 2D / 3D", False),
            ("", "", "", False),

            ("[Mouse & Shortcuts (laser on screen)]", "", "", True),
            ("Right trigger", "Full press click", "Left mouse click", False),
            ("Right trigger", "Hold", "Left mouse button hold", False),
            ("Left trigger", "Full press click", "Right mouse click", False),
            ("Left trigger", "Hold", "Right mouse button drag", False),
            ("Right stick U/D", "Hold & push", "Mouse wheel scroll", False),
            ("Left stick U/D", "Hold & push", "Keyboard Up/Down arrows", False),
            ("Left stick L/R", "Hold & push", "Keyboard Left/Right arrows", False),
            ("Left stick press", "Short press", "Ctrl+C", False),
            ("Left stick press", "Long press 1s", "Ctrl+X", False),
            ("Right stick press", "Short press", "Ctrl+V", False),
            ("Right stick press", "Long press 1s", "Enter key", False),
            ("", "", "", False),

            ("[Virtual Keyboard (keyboard visible only)]", "", "", True),
            ("Both Grips + laser on keyboard", "Hold & move", "Orbit keyboard around head", False),
            ("Right Grip + left stick L/R", "Hold & push", "Keyboard width resize", False),
            ("Right Grip + left stick U/D", "Hold & push", "Keyboard push/pull distance", False),
            ("Left Grip + right stick L/R", "Hold & push", "Keyboard yaw offset", False),
            ("Left Grip + right stick U/D", "Hold & push", "Keyboard pitch offset", False),
            ("Left Grip + left stick press", "Hold & move", "Keyboard sphere orbit", False),
            ("Left/Right trigger", "Half press", "Trigger key on keyboard", False),
            ("", "", "", False),

            ("[Controller Calibration (Developer)]", "", "", True),
            ("Right A+B buttons", "Hold both 0.5s", "Switch controller brand model", False),
            ("Right A+B buttons", "Hold both 5s", "Enter/exit calibration mode", False),
            ("Right B button", "Click in calibration mode", "Save calibration & exit", False),
        ]
        ENV_ROWS = [
            ("# Room Controller Operation Guide", "", "", True),
            ("", "", "", False),

            ("[Room & Panel]", "", "", True),
            ("Left Menu button", "Short press", "Cycle status panel: hidden/lower-left FPS/FPS + shortcut guide", False),
            ("Left Y button", "Short press", "Recenter to room screen/default position", False),
            ("Left Y button", "Long press 1s", "Switch room environment", False),
            ("Left X button", "Short press", "Show/hide virtual keyboard", False),
            ("Left X button", "Long press 1s", "Toggle environment skybox / black", False),
            ("Right A button", "Short press", "Toggle curved/flat screen", False),
            ("Right A button", "Long press 1s", "Cycle status panel: hidden/lower-left FPS/FPS + shortcut guide", False),
            ("Right B button", "Short press", "Toggle VDXR green / background", False),
            ("Right B button", "Long press 1s", "Show/hide operation guide", False),
            ("Both triggers", "Hold together 5s", "Disable/enable controllers; only this chord works while disabled", False),
            ("", "", "", False),

            ("[Depth & Visual]", "", "", True),
            ("Right Grip + left stick U/D", "Hold & push", "Adjust depth strength", False),
            ("Right Grip + right stick press", "Hold & click", "Reset depth strength", False),
            ("Left Grip + left stick press", "Hold & click", "Toggle 2D / 3D", False),
            ("", "", "", False),

            ("[Mouse & Shortcuts (laser on screen)]", "", "", True),
            ("Right trigger", "Full press click", "Left mouse click", False),
            ("Right trigger", "Hold", "Left mouse button hold", False),
            ("Left trigger", "Full press click", "Right mouse click", False),
            ("Left trigger", "Hold", "Right mouse button drag", False),
            ("Right stick U/D", "Hold & push", "Mouse wheel scroll", False),
            ("Left stick U/D", "Hold & push", "Keyboard Up/Down arrows", False),
            ("Left stick L/R", "Hold & push", "Keyboard Left/Right arrows", False),
            ("Left stick press", "Short press", "Ctrl+C", False),
            ("Left stick press", "Long press 1s", "Ctrl+X", False),
            ("Right stick press", "Short press", "Ctrl+V", False),
            ("Right stick press", "Long press 1s", "Enter key", False),
            ("", "", "", False),

            ("[Virtual Keyboard (keyboard visible only)]", "", "", True),
            ("One/Both Grips + laser on keyboard", "Hold & move", "Orbit keyboard around head", False),
            ("Right Grip + left stick L/R", "Hold & push", "Keyboard width resize", False),
            ("Right Grip + left stick U/D", "Hold & push", "Keyboard push/pull distance", False),
            ("Left Grip + right stick L/R", "Hold & push", "Keyboard yaw offset", False),
            ("Left Grip + right stick U/D", "Hold & push", "Keyboard pitch offset", False),
            ("Left Grip + left stick", "Hold & push", "Keyboard sphere orbit", False),
            ("Left/Right trigger", "Half press", "Trigger key on keyboard", False),
            ("", "", "", False),

            ("[Controller Calibration (Developer)]", "", "", True),
            ("Right A+B buttons", "Hold both 0.5s", "Switch controller brand model", False),
            ("Right A+B buttons", "Hold both 5s", "Enter/exit calibration mode", False),
            ("Right B button", "Click in calibration mode", "Save calibration & exit", False),
        ]
    return ROWS, ENV_ROWS
